### ISSUE TITLE
We could monitor application usage in the dashboard

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Dashboard#103]
By this I mean, for example:
http://validator.iatistandard.org/logs/view_log.php?days=70

or maybe some simple google analytics - although I would be careful and think about what it is that we really want to monitor - hits might not be useful, but with the validator above it seems clear that over the last 70 days, people mainly fetch, there are a significant number of uploads and not a lot of pasting.

For other software projects it might be worth having some key figures on the dashboard. This also helps us build good monitoring into the software projects. Maybe.

**Comment by allthatilk** [comment]
Google analytics does this.
