### ISSUE TITLE
Apply validator Rulesets against a set of activities

### ISSUE THREAD

**Issue by johnadamsDFID** [IATI/IATI-Dashboard#132]
As a donor, I want to be able to run a validator Ruleset against a set of activities (e.g. the activities identified in #131), so that I can understand which of my suppliers comply with the requirements I have set.

**Comment by hayfield** [comment]
This can be done using [pyIATI](https://github.com/IATI/iati.core).

This is currently in a [development branch](https://github.com/IATI/iati.core/tree/dev), though is ready to go to the master branch once a couple of changelogs and such have been merged down.
