### ISSUE TITLE
Add currency conversion

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Dashboard#154]
This is required for the [coverage](https://github.com/IATI/IATI-Dashboard/issues/139) ~~and [forward looking](https://github.com/IATI/IATI-Dashboard/issues/141)~~ tabs.

**Comment by dalepotter** [comment]
Related to https://github.com/IATI/IATI-Dashboard/issues/348, where work has been done to implement basic currency conversions.

**Comment by dalepotter** [comment]
Currency conversion values need to be added for 2016 though: https://github.com/IATI/IATI-Stats/blob/c6ac2e4664bb936985e3bf470fdfb4a7451db170/helpers/currency_conversion/exchange_rates.csv#L27

Also, the whole process could be made more robust. Also, there are errors being generated in the log files related to currency conversion code that need resolving.

**Comment by dalepotter** [comment]
Remaining action to to add a test of the `get_USD_value()` function.

**Comment by hayfield** [comment]
@dalepotter Is this complete?

**Comment by Ocre42** [comment]
The coverage section of the dashboard is under review, so we'll get back to this issue once that has been resolved
