### ISSUE TITLE
How often are elements used?

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Dashboard#17]
It might be good to know:
How many activities are reporting a certain element across 
a) the entire dataset
b) at individual publisher level
c) perhaps at county or region level

This is complicated by hierarchy, so not every activity needs to report in exactly the same way.

Typical questions we might want to answer would be:
How many activities (maybe at the lowest reported hierarchy) are reporting budgets/results/

This idea does need more work to be a more generic proposal, but I think getting e.g. budgets and results reporting right might be useful in itself.

**Comment by dalepotter** [comment]
Closing this ticket in light of the existence of http://dashboard.iatistandard.org/elements.html and comments above.
