### ISSUE TITLE
Forward-looking publisher stat

### ISSUE THREAD

**Issue by bill-anderson** [IATI/IATI-Dashboard#280]
*  Budgets can be reported at any hierarchical level
*  Each publisher must only report budgets at a single level
*  Code needs to figure out what level is being used
*  If multiple levels are being used this should be flagged and only lowest level should be calculated
*  If single level is used than only activities at that level should be used to calculate denomenator

Working example is DFID. Budgets are only reported at level 1

**Comment by Bjwebb** [comment]
Closing as a duplicate of https://github.com/IATI/IATI-Dashboard/issues/312
