### ISSUE TITLE
Implement recipient language calculation

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Dashboard#281]
Splitting this out of https://github.com/IATI/IATI-Dashboard/issues/275 as it is more complicated than most of the others.

**Comment by dalepotter** [comment]
The latest methodology for this is suggested on a [Discuss post which outlines proposals](http://discuss.iatistandard.org/t/indicator-coverage-methodology-consultation-space/357/7) circulated amongst the IATI steering committee.  The upshot of this is that the recipient language methodology:

> "will compare the language of the title and description against the recipient country, irrespective of the publisher’s ‘home’ language. Only activities targeted at a single recipient country will be assessed."

**Comment by dalepotter** [comment]
In addition to the above methodology, and following discussion with @bill-anderson, publishers who do not have any activities targeted at only one recipient-country will be given the benefit of the doubt and assigned 100% on the dashboard.
