### ISSUE TITLE
Comprehensiveness: Summary

### ISSUE THREAD

**Issue by bill-anderson** [IATI/IATI-Dashboard#284]
Add a Summary tab which contains 4 columns:

*  Core (Average all Core columns)
*  Financials (Average all  Financials columns)
*  Valued Added (Average all VA columns)
*  Average (Average of three above values (NOT average of all stats columns))

Can you write this in a way that we can easily mess with weightings in future (eg, count core twice and divide by 4)

**Comment by dalepotter** [comment]
Closing this issue, given that @bill-anderson has looked over the Comprehensiveness pages before the last IATI Steering Group meeting.
