### ISSUE TITLE
Dashboard trying to downloaded "deleted" files

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Dashboard#288]
http://dashboard.iatistandard.org/download.html - the scuk files are actually of state "deleted" on the Registry.  

NB: I've since purged these files, so they are not on the Registry, but thought I'd report this

**Comment by Bjwebb** [comment]
Seems that the dashboard is pulling from my old gist, not the new iati-bot one. Will fix shortly.

**Comment by Bjwebb** [comment]
I think this is now fixed.
