### ISSUE TITLE
2.01 as an expected version

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Dashboard#295]
Am I right in thinking that 2.01 should now be expected on http://dashboard.iatistandard.org/versions.html ?

**Comment by Bjwebb** [comment]
I've not deployed the new updates to live yet. Once I have, it should be.

**Comment by Bjwebb** [comment]
http://dev.dashboard.iatistandard.org/versions.html should now be correct. Planning on deploying to live today.

**Comment by Bjwebb** [comment]
Should be fixed on live now http://dashboard.iatistandard.org/versions.html
