### ISSUE TITLE
Publishing statistics page lists (none)

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Dashboard#300]
http://dashboard.iatistandard.org/timeliness.html

There are a few entries for (none) , which seem to be deleted publishers

**Comment by Bjwebb** [comment]
Yes, these are deleted publishers.

Do you have a suggestion for what the display behaviour should be, given that I can't look the name up on the registry, since that information has been deleted. We could just not display deleted publishers, or just use their registry slugs...

**Comment by stevieflow** [comment]
Dont display them.
