### ISSUE TITLE
Publishing stats: Show percentages as decimal?

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Dashboard#302]
eg: http://dashboard.iatistandard.org/forwardlooking.html

Spain do have forward looking budgets, but in 2016 this is around 0.04% 

Perhaps the percentage figures could be expressed as decimal, to help indicate this ?

**Comment by hayfield** [comment]
@bill-anderson Do we care to do this?

**Comment by stevieflow** [comment]
@akmiller01 I can't see any percentages on http://publishingstats.iatistandard.org/forwardlooking.html - did this get implemented or just closed, as it will not be addressed.  Apologies for checking!

**Comment by akmiller01** [comment]
My apologies for not marking the issue with an explanation @stevieflow. I ended up closing most feature enhancement issues for the Dashboard and Publishing Stats, and only kept open bug fixes. I don't think there's any plans to enhance these tools, so I considered most suggestions for new features to be out of scope.

This kind of decimal rounding issue is worth bearing in mind for the next iteration of this tool, however. Maybe at some point we could put together a list of ideas for improvements, what worked, what didn't work, and bundle that together into the resources used to plan the next thing.

**Comment by andylolz** [comment]
Github offers a “close as not planned” issue status these days:
<img width="317" alt="Screenshot 2022-11-17 at 14 44 28" src="https://user-images.githubusercontent.com/464193/202476782-b15f6465-c8ac-47a6-aa2d-90b8094176a3.png">

**Comment by stevieflow** [comment]
Thanks for the update @akmiller01 - useful to know.  

Some time ago we did also fork a copy of the dashboard at https://github.com/codeforIATI/analytics - and then fix a bunch of issues: https://github.com/codeforIATI/analytics/pulls?q=is%3Apr+is%3Aclosed

This got rid of some of the annoyances on the Dashboard - such as the persistent notice to not deal with code vocabularies

This runs successfully at https://analytics.codeforiati.org/

Ideal for me would be we just have one dashboard, that *works* !

**Comment by stevieflow** [comment]
@akmiller01 just wanted to share that @andylolz has implemented this in our fork of the dashboard: https://github.com/codeforIATI/analytics/issues/67

Could there be a way for you to pick up this PR and apply to to the dashboard , perhaps ?
