### ISSUE TITLE
Show progress during fetch_data.py process

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Dashboard#305]
When you run fetch_data.py, it can take a while, and maybe look like the process has hung.

Some sort of progress indicator could be useful.

**Comment by dalepotter** [comment]
MVP approach would be to add some text saying 'This process may take some time'

**Comment by hayfield** [comment]
`ls -l` shows when things were last changed, so it can be seen whether things are still happening in the relevant folder (which is known).
