### ISSUE TITLE
Update budget hierarchy methodology on forward looking tab

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Dashboard#312]
From Bill:
> For publishers using multiple levels
> * Budgets do not have to be reported at the lowest level
> * Budgets must only be reported at one level
> * Any publishers reporting budgets at more than one level should be redflagged and all budgets and all current activities at all levels should be counted in the score
> * For publishers reporting correctly at one level, only current activities at that level should be counted in the score

**Comment by Bjwebb** [comment]
I've implemented an update to the code, that can be seen at http://dev.dashboard.iatistandard.org/forwardlooking.html

Still to do:
- [ ] Check with Bill that all activities should be shown in the activity count columns for publisher with multiple hierarchies but no budgets
- [ ] Update the text on the page to describe the new methodology

**Comment by caprenter** [comment]
Passing this onto @bill-anderson

**Comment by dalepotter** [comment]
@iatisupport - could you confirm what next actions are needed for this ticket.

Many thanks.

**Comment by iatisupport** [comment]
I can confirm that budgets can occur at more than one level in a hierarchy. As a result they should therefore be handled as per the proposal by @dalepotter at http://discuss.iatistandard.org/t/indicator-comprehensive-methodology-consultation-space/356/9

**Comment by dalepotter** [comment]
Thanks @iatisupport for confirming. The change that you highlighted is detailed further in https://github.com/IATI/IATI-Dashboard/issues/312 and which itself has been effected in commit 24b8b59.

With this in mind, I'll now close this issue.
