### ISSUE TITLE
NACE Sector Codes Reported As Not On Codelist 

### ISSUE THREAD

**Issue by iatisupport** [IATI/IATI-Dashboard#313]
A publisher is currently only publishing NACE sector codes for their activities. However, the dashboard is reporting them as an error in that the codes are not on the (DAC) codelist. See http://dashboard.iatistandard.org/publisher/eib.html

**Comment by Bjwebb** [comment]
Thanks for the bug report. You're right that this is incorrect behaviour on the part of the dashboard.

It's been previously reported at https://github.com/IATI/IATI-Dashboard/issues/174, so I'm closing this issue as a duplicate. It's not a small thing to fix, so isn't likely to be resolved soon. However, I am currently looking at adding a warning about this behaviour - https://github.com/IATI/IATI-Dashboard/issues/277 - which I am hoping to complete today or tomorrow.

**Comment by Bjwebb** [comment]
I've added a note to the dev dashboard about this now:
http://dev.dashboard.iatistandard.org/publisher/eib.html#p_codelists

This should be deployed to live over the next few days.
