### ISSUE TITLE
Dashboard Reports Different Percentage Values For location/point/pos

### ISSUE THREAD

**Issue by iatisupport** [IATI/IATI-Dashboard#315]
The dashboard (as at 20/3/15) reports that EC - Foreign Policy Instruments (ec-fpi) has 343 instances of location/point/pos - see http://dashboard.iatistandard.org/publisher/ec-fpi.html. It also reports that there are a total of 441 activities. This therefore calculates as approx 78% which is the same value (78%) of activities that d-portal reports for EC FPI as having specific location details. 

However, the dashboard Added Value view for EC FPI reports only 73% of activities as having 'Geographic Coordinates'. I have checked the data for EC FPI and can find no instances of the <pos> element being empty or set to '0 0' so it would be good to know why the value of 73% is being reported? Also if a small percentage of the data is invalid should the dashboard actually be reporting 73 (78) instead of just 73?

**Comment by dalepotter** [comment]
Hi Wendy, just came across this one. Having taken a look at the code for this, it appears that the coordinates found in `location/point/pos` are being piped through [this function to check that they are valid](https://github.com/IATI/IATI-Stats/blob/master/stats/dashboard.py#L188-L200).

Looking back at this, would you be able to confirm that ec-fpi's coordinates appear to be valid?

**Comment by iatisupport** [comment]
Having re-investigated this one it looks like the difference occurs because the publisher page includes counts for all published activities whereas the comprehensiveness pages are only looking at 'current' activities. Therefore I am happy for this issue to be closed
