### ISSUE TITLE
Inconsistent data on Comprehensiveness page

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Dashboard#316]
The Comprehensiveness page is showing incorrect data in the 'Transaction - Disbursement or Expenditure' column, with many figures showing as zero.

This issue can be viewed when exploring one of the organsations listsed, for example 'Everychild'.  transactions. As of 2015-04-21 06:16:15, the dashboard page shows:
Transaction - Commitment: 100 
Transaction - Disbursement or Expenditure: -

An analysis of the raw data shows that this organisation should have at least one qualtifying active disbursement/expenditure transaction: http://aidstream.org/files/xml/evc-activities.xml

**Comment by YohannaLoucheur** [comment]
Canada's DFATD data is also showing incorrectly - we get 0 scores for eg Reporting Org, Titles, Descriptions etc. 

Any idea of what's going on or when this bug might be fixed?

**Comment by dalepotter** [comment]
This issue is now referenced here: https://github.com/IATI/IATI-Stats/issues/59
