### ISSUE TITLE
CSV download from Publisher Statistics - column headers

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Dashboard#317]
The CSV output from http://dashboard.iatistandard.org/timeliness_timelag.html (for example) has the columns:

![image](https://cloud.githubusercontent.com/assets/1209944/7476805/e9531e88-f347-11e4-92c4-c4cee744d077.png)

Hence - the column headers seem to be the wrong way round

**Comment by stevieflow** [comment]
I think this is on the two downloads on Timeliness

**Comment by dalepotter** [comment]
This is a duplicate of https://github.com/IATI/IATI-Dashboard/issues/340, which has since been resolved.
