### ISSUE TITLE
CSV download from Publisher Statistics - inclusion of deleted publishers

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Dashboard#318]
The CSV download from timeliness - http://dashboard.iatistandard.org/timeliness.html - includes publishers that are deleted.  These publishers are not included in other CSV downloads, meaning it is difficult to cross-match the data

![image](https://cloud.githubusercontent.com/assets/1209944/7477787/fa43f13a-f34d-11e4-8f06-77365d0ec3dd.png)

**Comment by hayfield** [comment]
Covered by #372
