### ISSUE TITLE
Contextual pop-up windows should close when another link clicked

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Dashboard#323]
Example on this page, when clicking any of the 'Publisher' links: http://dashboard.iatistandard.org/codelist/1/budget_@type.html

**Comment by dalepotter** [comment]
Can be closed when @andylolz pull request is tested on the dev server and deployed to live.

**Comment by andylolz** [comment]
Just came across this issue again. It appears to be fixed now, and can be closed 🚀
