### ISSUE TITLE
Dashboard not updating

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Dashboard#325]
Hi

As of 26th June we have:

> Generated on 2015-06-13 07:08:00 +0100 from data downloaded 2015-06-13 02:11:49 +0100.

Is something broken?

**Comment by dalepotter** [comment]
Related to https://github.com/IATI/IATI-Dashboard/issues/324

**Comment by dalepotter** [comment]
As an update to this one, a manual update is being done on the Dashboard each day until a fix for the automatic nightly process is confirmed.

The dashboard is now up-to-date as of 2015-06-30 11:41:26 +0100.

**Comment by dalepotter** [comment]
This should now be resolved
