### ISSUE TITLE
Add org type to CSV download of publishing stats

### ISSUE THREAD

**Issue by jonihillman** [IATI/IATI-Dashboard#334]
Would be really helpful to have this for analysis and reports so can more easily say 'X multilaterals are publishing forward looking data' etc.

e.g. http://dashboard.iatistandard.org/forwardlooking.html. Not sure we need to add org type to the Dashboard tables as might start getting a bit cluttered but think useful to add to CSV.

Might also be worth using this as an opportunity to discuss what other fields could be useful to add to CSV.

**Comment by hayfield** [comment]
Exists for `Summary Stats`, but not the others.
