### ISSUE TITLE
Fix JSON file links on Publisher page

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Dashboard#335]
On http://dashboard.iatistandard.org/publisher/sida.html#p_codelists links to raw JSON files

http://dashboard.iatistandard.org/stats/current/aggregated/sida/codelist_values.json should be: http://dashboard.iatistandard.org/stats/current/aggregated-publisher/sida/codelist_values.json

http://dashboard.iatistandard.org/stats/current/aggregated/sida/elements.json should be:
http://dashboard.iatistandard.org/stats/current/aggregated-publisher/sida/elements.json

Both links are currently going to 404 errors.

**Comment by andylolz** [comment]
This looks fixed & closable to me.

![rkhcv4hony](https://cloud.githubusercontent.com/assets/464193/23903485/985dc4e2-08bc-11e7-8e16-bd495c1547c7.gif)

**Comment by dalepotter** [comment]
Thanks for flagging @andylolz 

Will not close!
