### ISSUE TITLE
Add 'date first published' to CSV downloads in Dashboard and/or in Dashboard tables

### ISSUE THREAD

**Issue by jonihillman** [IATI/IATI-Dashboard#336]
Would be really useful to finally get the date each org first published. This is really useful for reporting etc and to show how the number of publishers has changed over time.

We record this data manually in the CRM but need to find a way to automate. I raised this with Ben and co in the past but apparently it's very difficult for the Registry to show this. Would be great if someone was able to look into this.

Happy to discuss if more info required.

**Comment by dalepotter** [comment]
There is already a rough* calculation of the date first published, for example the first date listed (`2015-07-31 03:33:25 +0100`) for publisher 'Hand in Hand International' (registry id 'handinhand'): http://dashboard.iatistandard.org/stats/gitaggregate-publisher-dated/handinhand/most_recent_transaction_date.json

* This date will be inaccurate as this only lists when the new data was first pickted up by the nightly process using the IATI-Stats code. For the example given, we know that Hand in Hand International first published on 20th July 2015.

**Comment by dalepotter** [comment]
The CKAN Registry API can also list the date that a dataset was created, for example in the [Registry metadata for Hand in Hand's data] (http://iatiregistry.org/api/3/action/package_search?q=organization:handinhand): `"created": "2015-07-30T12:19:28.142191"`

If an organisation has many files, then there might need to be some logic around finding the earliest date.  And also checking that the corresponding XML file is not empty (or contains at least one activity if we want to exclude badly-formed data).

**Comment by dalepotter** [comment]
This is related to https://github.com/IATI/IATI-Dashboard/issues/314
