### ISSUE TITLE
Lists should be ordered alphabetically by default

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Dashboard#338]
All lists should be ordered alphabetically by default (according to the first column). 

This does occur in most cases, but there are some exceptions, for example on: http://dashboard.iatistandard.org/validation.html <- In the 'Count of files that fail validation, per publisher.' table.

![image](https://cloud.githubusercontent.com/assets/8247168/9955577/f4927e62-5de9-11e5-96cd-bda4e94e8f45.png)

**Comment by hayfield** [comment]
The example page is sorted alphabetically by registry ID - this seems pretty standard.
