### ISSUE TITLE
Frequency calculation when publishers change their name

### ISSUE THREAD

**Issue by markbrough** [IATI/IATI-Dashboard#353]
When an organisation changes their IATI Registry publisher ID - e.g. EC DEVCO changes it from `eu` to `ec-devco` - they get counted as a new publisher and therefore can only score as "annual" frequency of publication. Would it make sense to map between these publisher IDs when it is the same organisation, so that in this instance, they could continue to score "monthly"?

![frequency-screenshot](https://cloud.githubusercontent.com/assets/688113/11060364/9bc504d0-8797-11e5-8bc6-0de71c99b32a.png)

Possibly relevant function:

https://github.com/IATI/IATI-Dashboard/blob/master/timeliness.py#L54

**Comment by dalepotter** [comment]
Hi Mark, many thanks for alerting us to this issue. I’ve put through a commit containing a file to maps known publishers who have changed their registry ID and some code to merge the data to the publisher’s current registry ID. 

My approach to this [includes making an in-memory copy of all the gitaggregate data](https://github.com/IATI/IATI-Dashboard/blob/9fd2b15caf19211c86c00fd8a91357b8996816dc/data.py#L120-L125). This is a slow process and there may be a better approach to solving this problem - we're open to ideas on this.

In the meantime, this code is being deployed on a development server and will be tested in the next 24 hours.  I will update on progress once the output has been generated and reviewed.

**Comment by dalepotter** [comment]
As an update to this, it seems that - as suspected - this approach has indeed caused memory issues on our development server.  Therefore changes made in 9fd2b15 are not considered a viable fix. A new approach to compiling publishers with changed registry IDs is now being explored with high priority. For information, this will involve modifying the behaviour of the [JSONDir() object]( https://github.com/IATI/IATI-Dashboard/blob/master/data.py#L35).

**Comment by dalepotter** [comment]
As a formal update to this issue, we now have a quick fix in place, and the code in ba61a09 has now been deployed to dev and live servers on a short-term basis, with the following results:

![image](https://cloud.githubusercontent.com/assets/8247168/12231205/97605cdc-b84d-11e5-95c3-f57a11a9ac2e.png)

This is only considered a short-term fix, in favour of modifying the behaviour of the [`JSONDir()` object]( https://github.com/IATI/IATI-Dashboard/blob/master/data.py#L35) to pull in a merged data object based on data under the old and new registry IDs. This should also resolve the occurance of this issue on the publisher data pages: http://dashboard.iatistandard.org/publisher/ec-devco.html

This work is ongoing locally.  When tested, it will replace the current fix, based on code in ba61a09.

**Comment by dalepotter** [comment]
I'm pleased to report that commit f74055a now resolves this problem in a robust manner.  Alongside the timeliness frequency page, the fix is now represented on individual publisher pages, with graphs now recognising data published under old registry identifiers.

![image](https://cloud.githubusercontent.com/assets/8247168/12582454/1fcbcc8a-c435-11e5-9d2f-1d8b53ada879.png)
