### ISSUE TITLE
Joining stats when publishers change reporting org

### ISSUE THREAD

**Issue by bill-anderson** [IATI/IATI-Dashboard#358]
EU/EC publishers are being unfairly penalised for changing reporting-org id

**Comment by dalepotter** [comment]
This appears to be a duplicate of https://github.com/IATI/IATI-Dashboard/issues/353

**Comment by dalepotter** [comment]
This issue appears to impact upon the timeliness page, do post if there are any other pages where publishers are being unfairly penalised?
