### ISSUE TITLE
"Values used" count doesn't match

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Dashboard#364]
E.g. default currency has 0 "Values used, on codelist" at http://dashboard.iatistandard.org/codelists.html, but 
http://dashboard.iatistandard.org/codelist/1/@default-currency.html shows several.

**Comment by dalepotter** [comment]
Lovely! Thanks for that - the fix in 6e05dfc should resolve this, and will be rolled out to dev shortly.

Deployment to the live server expected when the `early-2016-sprint` branch is merged to live, within a couple weeks, if not before.
