### ISSUE TITLE
Results In Hierarchy Not Being Reported For Value Added Comprehensiveness

### ISSUE THREAD

**Issue by iatisupport** [IATI/IATI-Dashboard#367]
The US currently use three levels of hierarchy for their reporting. Level 1 = Theme, Level 2 = Intervention and Level 3 = Project. They have included some results data at Level 2 (see http://beta.foreignassistance.gov/assets/IATI/Algeria.xml) however the dashboard is reporting results on the 'Value added' comprehensiveness page ( http://dashboard.iatistandard.org/comprehensiveness_valueadded.html) as zero

**Comment by dalepotter** [comment]
As with #368, comprehensiveness assessments are based solely on data that is located within activities at the bottom hierarchy.

The only public reference that I can find to this is located with the [pseudocode section](http://dashboard.iatistandard.org/comprehensiveness.html#h_pseudocode) of each of the comprehensiveness pages.  Perhaps we should make this clearer, in line with how we describe that only 'current' activities are used for assessments:

![image](https://cloud.githubusercontent.com/assets/8247168/12558717/014d42e0-c389-11e5-98ec-0c2a165a0607.png)

I'm unsure about rationale for only making assessments based on bottom hierarchy activities - perhaps @bill-anderson might be able to explain, or point to a consultation/discussion post (I've not located one on my searches)?
