### ISSUE TITLE
Budget Data In Published File Reported As Zero On Forward Looking Comprehensiveness

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Dashboard#368]
The US have included some budget data in their published files see http://beta.foreignassistance.gov/assets/IATI/MCC_Nepal.xml. Whilst this forward looking information is reported on the 'Forward Looking' page at http://dashboard.iatistandard.org/forwardlooking.html the score for budget information is zero on the 'Financials' tab of the Comprehensiveness page at http://dashboard.iatistandard.org/comprehensiveness_financials.html

**Comment by dalepotter** [comment]
Thanks for raising this issue. According to my analysis on this (based on today's data), the US publish 
156997 activities in total ([source](http://dashboard.iatistandard.org/stats/current/aggregated-publisher/unitedstates/activities.json)), with 141340 of these are classed as current for comprehensiveness calculations ([source](
http://dashboard.iatistandard.org/stats/current/aggregated-publisher/unitedstates/comprehensiveness_denominator_default.json)).  Of these 'current' activities, 4818 contain budget data ([source](http://dashboard.iatistandard.org/stats/current/aggregated-publisher/unitedstates/comprehensiveness.json)), which calculates as 0.03% of 'current' activities.  The dashboard rounds this up to 1%:

![image](https://cloud.githubusercontent.com/assets/8247168/12551650/fa5bacee-c363-11e5-9880-7d9cf480bc20.png)

For interest, the [MCC_Nepal.xml dataset](http://beta.foreignassistance.gov/assets/IATI/MCC_Nepal.xml) that is referenced, contains 18 activities ([source](http://dashboard.iatistandard.org/stats/current/aggregated-file/unitedstates/unitedstates-np2/activities.json)), all 18 of which are classed as 'current activities' ([source](http://dashboard.iatistandard.org/stats/current/aggregated-file/unitedstates/unitedstates-np2/comprehensiveness_denominator_default.json)). 8 of these contain budget data ([source](http://dashboard.iatistandard.org/stats/current/aggregated-file/unitedstates/unitedstates-np2/comprehensiveness.json)).

Do let me know if we spot any evidence of xml data being incorrectly calculated, based on these numbers and happy to look into this further. In the meantime, I'll mark this issue as closed for the time being.

**Comment by dalepotter** [comment]
In terms of hierarchies, this issue is related to https://github.com/IATI/IATI-Dashboard/issues/367

**Comment by dalepotter** [comment]
A proposal to amend the methodology in this regard is detailed here: http://discuss.iatistandard.org/t/indicator-comprehensive-methodology-consultation-space/356/7

**Comment by dalepotter** [comment]
An issue has been spotted in cases where the `by_hierarchy.json` file contains data such as this, the incorrect value is being returned for `get_hierarchy_with_most_budgets()`

```
{
  "1": {
    "activities": 596, 
    "comprehensiveness": {}, 
    "comprehensiveness_denominator_default": 0, 
    [...]
  }, 
  "2": {
    "activities": 757, 
    "comprehensiveness": {
      "activity-date": 679, 
      "activity-status": 679, 
      "activity-website": 0, 
      "budget": 0, 
      [...]
    }, 
    "comprehensiveness_denominator_default": 679, 
   [...]
   }
}
```

In this case, a return value of `1` was received, when it should logically be `2` (as the `comprehensiveness_denominator_default` = 0 in hierarchy 1). This should be changed.
