### ISSUE TITLE
Show Count Of Current Activities on Forward Looking & Comprehensive Pages

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Dashboard#371]
The figures displayed on both the Forward looking and Comprehensivness pages of the Publishing Statistics are both calculated from the number of 'current' activities rather than the total number of published activities. Therefore it would be useful to display the number of  'current' activities that have been used to calculate the relevant statistics in order to aid data users in understanding how the figures have been arrived at

**Comment by allthatilk** [comment]
@wendyrogers is this still an issue?
