### ISSUE TITLE
Impact On Dashboard When Removing Publisher Accounts From The Register

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Dashboard#372]
As part of managing the IATI registry it is necessary to remove the publisher accounts for two companies that have since merged and become a completely separate company that is already publishing in its own right (and has also taken on the data originally published by the original two companies).

What action is therefore required to remove the reference to the two original companies from the dashboard?

**Comment by iatisupport** [comment]
Just to aid investigation into this one the publisher 'United Network of Young Peacebuilders' is still showing on the timeliness dashboard page - http://dashboard.iatistandard.org/timeliness.html even though they were removed from the IATI registry more than a year ago
