### ISSUE TITLE
Modify coverage table in line with new proposal

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Dashboard#375]
In line with the comments listed on the Coverage page, as well as proposals listed in the [Indicator Coverage Methodology - consultation space] (http://discuss.iatistandard.org/t/indicator-coverage-methodology-consultation-space/357/6), the coverage table should be modified to implement the proposal listed in the [accompanying google doc](https://docs.google.com/spreadsheets/d/1v0aeX3PX6Yh3h3ZYUT8GU2NHuaWHQ75wIel3p2QzrDo/edit#gid=1892265246).

**Comment by iatisupport** [comment]
One clarification to make re The IATI Spend as a percentage of the reference spending or the offical forecast. This value is based on whichever is the greatest result from the following calculations:

2014 IATI Spend / 2014 Reference Spend
2015 IATI Spend / 2015 Reference Spend
2015 IATI Spend / 2014 Reference Spend
2015 IATI Spend / 2015 Official Forecast

However if both IATI Spend and Reference Spend are both present for 2014 and 2015 then the calculation for

2015 IATI Spend / 2014 Reference Spend

can be omitted

**Comment by dalepotter** [comment]
This is now added and will become visible when the Dashboard next fully regenerates.
