### ISSUE TITLE
Transaction tracability assessments for donor publishers

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Dashboard#377]
Donor publishers who do not need to report any incoming funds should not be assessed on traceability.

Suggested logic for identifying such activities is to identify where the IATI organisation identifier in the reporting-org element matches the identifier listed in any participating-org element (where the role attribute of the participating org is either '1' ('Funding') or '3' ('Extending').  However, this should not apply to activities where the reporting org is also listed as a participating-org with type '4' ('Implementing').

Activities fulfilling this condition will be given full credit for the transaction traceability calculations.

Pseudocode for this would be:

```
For each activity:
    If (participating-org[@role='1|3']/@ref == reporting-org/@ref)
       AND (participating-org[@role='4']/@ref != reporting-org/@ref):
       Then, assign 100% for transaction/tracability
```

**Comment by allthatilk** [comment]
@dalepotter is this still a thing?
