### ISSUE TITLE
Add Dashboard support for v2.02

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Dashboard#379]
Add Dashboard support for v2.02 of the IATI standard. Suggest follow the checklist of items in https://github.com/IATI/IATI-Dashboard/issues/234

Currently arises as an issue as many GAVI files are failing validation as they are published in v2.02: http://dashboard.iatistandard.org/publisher/gavi.html

![image](https://cloud.githubusercontent.com/assets/8247168/12781431/45d5ad14-ca6c-11e5-8504-192229bb5c68.png)

**Comment by rory09** [comment]
Remember: `Transaction - Commitment` column of Comprehensiveness > Financials needs to allow for [`transaction/transaction-type/@code`](http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/transaction/transaction-type/#iati-activities-iati-activity-transaction-transaction-type-code) to have [a value of 11](http://iatistandard.org/202/codelists/TransactionType/).

**Comment by dalepotter** [comment]
With reference to `Comprehensiveness` > `Financials` > `Transaction - Commitment`, this is the subject of IATI/IATI-Dashboard#397, and was specifically resolved in commit IATI/IATI-Dashboard@7ecb16e.

With this in mind, I'll close this issue.
