### ISSUE TITLE
List of elements includes URLs

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Dashboard#381]
Related to #123, there are number of rows on the [Elements](http://dashboard.iatistandard.org/elements.html) page which show URLs within the element path:

![image](https://cloud.githubusercontent.com/assets/8247168/12947042/9920a544-cff0-11e5-9e74-3001c336d6bc.png)

This probably relates to namespace extensions but needs to be investigated nonetheless.

**Comment by hayfield** [comment]
This is how use of namespace extensions is monitored.
