### ISSUE TITLE
Add 'aid type' to comprehensiveness (value added) calculations

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Dashboard#383]
As proposed in this Discuss post: http://discuss.iatistandard.org/t/indicator-coverage-methodology-consultation-space/357/7 and as part of a proposal that was circulated to IATI Steering group members.

## Methodology:
Proportion of a publishers' current activities which have i) data and ii) valid data in either of the following fields
- `iati-activities/iati-activity/default-aid-type/@code`
- `iati-activities/iati-activity/transaction/aid-type/@code`

**Comment by iatisupport** [comment]
Also just to clarify that a score will be given if
1) aid-type is present at the activity level
2) aid-type is present on all transactions if aid-type is used at the transaction level
