### ISSUE TITLE
Prevent Publishers With Invalid Data Getting High Scores For Coverage

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Dashboard#386]
It is currently possible for a publisher with invalid data to score 100% for coverage because their 'incorrect' data enables a high spend ratio (sometimes 100%+)  to be calculated. Therefore in order to initially prevent this happening we should implement a mechanism that allows the IATI Technical Team to mark the publisher as having incorrect data so that they only receive a score for coverage of 20% 

A publisher will only be marked as such when their data has been specifically checked and a data issue has been positively identified

**Comment by dalepotter** [comment]
To implement this:

- Add one column to the spreadsheet of coverage reference data (perhaps called 'data error (downgrade to 20%')
- Add one column to log the data ticket number, where the presence of invalid data has been alerted to the publisher
- Means of pulling this data though to the Dashboard code

**Comment by iatisupport** [comment]
Two columns now added to coverage spreadsheet. They are
Data error (downgrade to 20%') - values set to 'Y' or blank
Data error Zendesk Ticket
