### ISSUE TITLE
Use Commitment Transactions To Calculate Coverage IATI Spend For DFIs

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Dashboard#387]
As DFI's are generally unable to publish disbursement and expenditure transactions while an activity is in progress, their coverage IATI Spend values should instead be calculated by using the value of their commitment transactions

**Comment by dalepotter** [comment]
Next steps:

- Add a separate file to list DFI registry IDs
- @iatisupport to provide an initial list

**Comment by iatisupport** [comment]
Initiali list of DFI's to include:

CDC Group
European Investment Bank (EIB)
European Bank Of Reconstruction & Development (EBRD)

**Comment by dalepotter** [comment]
This issue is now put though to the codebase. There is a csv file 'dfi_publishers.csv' in the IATI-Dashboard repository which lists known DFIs.  This can be added to and will be reflected in new versions of the Dashboard when the code is deployed and the site regenerated.

**Comment by dalepotter** [comment]
I've now added the incoming funds and commitments to the output of `sum_transactions_by_type_by_year.json`, meaning that commitments by [DFI organisations](https://github.com/IATI/IATI-Dashboard/blob/master/dfi_publishers.csv) should be accurately counted in new versions of the Dashboard (from the point when the site next regenerates).
