### ISSUE TITLE
Exclude Activities That Are Soon To End From Forward Looking Calculations 

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Dashboard#389]
If an activity is it its last year of operational works then it should not be included in the calculations for current activities with forward looking data. Calculation to determine if this is the case:

```
If (end - 'today' <= 370 days):
    If end month >= 7:
        budget year = end year 
    Else:
        budget year = end year - 1
```

**Comment by iatisupport** [comment]
Just to confirm that the intended logic behind this check is to say that if the project is in the last 6 months that it is intended to run then don't include the activity in the forward looking checks

**Comment by dalepotter** [comment]
@ #

**Comment by dalepotter** [comment]
Remaining action is to add tests to the `test_forward_looking.py` in [IATI-Stats](https://github.com/IATI/IATI-Stats/blob/master/stats/tests/test_forward_looking.py).

**Comment by dalepotter** [comment]
Following a misinterpretation of requirements, the changes in 9b40a7d mean activities will only be excluded if the activity itself is determined to end within six months of when the code is run.  This now closes this issue.
