### ISSUE TITLE
Add Link From Coverage Page to US Exchange Rates

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Dashboard#390]
In order to aid transparency it would be useful to include a link from the dashboard coverage page so that publishers could see the exchange rates used for converting their figures into USD 

Rates at https://github.com/IATI/IATI-Stats/blob/master/helpers/currency_conversion/exchange_rates.csv

**Comment by hayfield** [comment]
@dalepotter @wendyrogers What is the status of this?
