### ISSUE TITLE
Amend Dashboard Software To Use Back End Database

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Dashboard#398]
The dashboard software currently takes a long time to run (eg 6+hours) and is also regularly subject to failed runs due to lack of available space or memory. In order to improve both the efficiency of the run times and to make the underlying data created and stored by the dashboard more accessible and searchable a back end database should be used to replace the multiple json files

**Comment by hayfield** [comment]
Yes

(though the size of the task makes leaving this issue open (and the consequential increase in Issue count by 1) makes us sad)

**Comment by hayfield** [comment]
...it is also only one of several major problems with the architecture, including use of `O(n^2)` algorithms to process activities, ease of parallelisation, and lack of testing.
