### ISSUE TITLE
Amend Activity iati-identifier Comprehensiveness Check To Allow For Publishers That Have Changed Organisation Identifier

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Dashboard#399]
If an organisation changes their organisation identifier they are required to keep the iati-identifier of all activities that have already been published the same and to add their 'old' organisation identifier to the other-identifier element. 

However, currently the check for iati-identifier only checks that the iati-identifier prefix matches the current reporting-org. As a result organisations that have currently changed their organisation identifier are scored down for the field for core comprehensiveness - see http://dashboard.iatistandard.org/comprehensiveness_core.html. Therefore the check for iati-identifier needs to be enhanced to also check if the activity identifier prefix matches that in the other-identifier element.

**Comment by markbrough** [comment]
Strongly support this change - we came across this issue already when trying to use the data in Bangladesh. Being able to break the IATI identifier down into the organisation identifier and their internal project code is important for being able to match projects where a donor has used their internal project code in the AIMS.

**Comment by dalepotter** [comment]
Just put this change though, which should be visible on the Dashboard when it next regenerates.

**Comment by wendyrogers** [comment]
Just to add that we should enhance the check for other-identifier to check for an @ref value of 'B1' - to indicate 'Previous Reporting Organisation Identifier'

**Comment by wendyrogers** [comment]
Also to add that as the use of the other-identifier element was only introduced at V2.01 we should not validate the activity-identifier prefix against reporting-org for publishers who are still publishing at V1.xx of the standard
