### ISSUE TITLE
Adjust Coverage Score To 20% When Spend Ratio > 120%

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Dashboard#400]
If Spend ratio is over 100% then generally something is wrong with the data. Either the reference figure is too low or there are data quality issues in the published data. Therefore allowing for a margin of error publishers will only score 20% if the spend ratio is > 120%

**Comment by dalepotter** [comment]
As an amendment to this issue, spend ratios of over 100% for bilateral DAC publishers will be treated as 100% PROVIDED THAT the cause of the higher ratio is not the result of invalid data noted by the dashboard.
