### ISSUE TITLE
Check For Commitment Transactions At Any Level Of A Hierarchy

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Dashboard#401]
Currently I understand that the dashboard only checks for commitment transactions at the lowest level of a hierarchy (as is the case for other transactions types). However, commitment transactions are allowed to occur at any level of a hierarchy (but only once within the hierarchy) so the dashboard checks will need to be enhanced to allow for this situations with commitments and relevant scores adjusted accordingly.

This check should also apply to Incoming Transaction types as well. See #397

**Comment by dalepotter** [comment]
A change has been put though which means that, for the calculation of the 'Transaction - Commitment' statistic, the Dashboard code will use the highest hierarchy that contains a transaction of type `Commitment`or `Incoming Commitment`.  If no hierarchy contains an above-defined commitment, the bottom hierarchy will be used for calculations.  

This change will be visible when the dev Dashboard next fully regenerates. 

In a related note, commit IATI/IATI-Stats@7ecb16e ensures that the issue in #397 (adjustments for the new `Incoming Commitment` transaction type) already applies to these changes.
