### ISSUE TITLE
Record Assessment Of Updated IATI Datasets For Date Of Publication

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Dashboard#406]
Currently, if a publisher updates and refreshes their published IATI datasets on the last day of the month, the files are actually assessed as for the first day of the next month. This is because the dashboard update software runs overnight from midnight and therefore records the date of update for when the dashboard update is run. 

However, the dashboard update software should assess the amended IATI datasets for the date that the dataset file was published.

**Comment by hayfield** [comment]
This is how the Dashboard works.

The only place this may reasonably impact is in the `Timeliness` calculation. In this situation, the flexibility in [the](http://dashboard.iatistandard.org/timeliness_timelag.html#h_assesment) [methodology](http://dashboard.iatistandard.org/timeliness.html#h_assesment) means that while it may take slightly longer to stabilise, there will be no impact longer-term so long as publishing is consistent.

The amount of work required to change this means it is a `wontfix`.
