### ISSUE TITLE
Add iati-activity/@humanitarian to booleans values reported by the IATI Dashboard

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Dashboard#413]
In order to support the work of the Grand Bargain it will be necessary to regularly check to see which publishers are using (ie set to 1) the v2.02 humanitarian marker (attribute of iati-activity) - http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/

Therefore please can we add the humanitarian marker onto the page of booleans reported on at http://dashboard.iatistandard.org/booleans.html

**Comment by benparkergit** [comment]
Does this tell the same story in a different format? http://dashboard.iatistandard.org/element/iati-activity_@humanitarian.html

**Comment by wendyrogers** [comment]
Thanks @benparkergit sort of but not quite? We need to know specifically which publishers have humanitarian set to 1 and I don't think you can easily tell from that page without looking at the data of each publisher using the attribute

**Comment by andylolz** [comment]
This is marked as resolved, but I don’t `@humanitarian` here yet:
http://dashboard.iatistandard.org/booleans.html

Is that expected? Does something need deploying?

**Comment by dalepotter** [comment]
Hi Andy, it's currently deployed on our [dev server](http://dev.dashboard.iatistandard.org/booleans.html) and it should be deployed to live on Thursday.

Maybe I shouldn't have closed this before we deployed to live!

**Comment by wendyrogers** [comment]
Please could the values for transaction/@humanitarian attribute also be added the boolean page

**Comment by hayfield** [comment]
The fix has now been deployed to live and http://dashboard.iatistandard.org/booleans.html will update when the live dashboard next regenerates.

A separate issue, [#416], has been created to track the addition of `transaction/@humanitarian`.
