### ISSUE TITLE
Modify title and description of Global Partnership Transparency Indicator Proposal page

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Dashboard#414]
According to @bill-anderson the title and description of the [Global Partnership Transparency Indicator Proposal](http://dashboard.iatistandard.org/transparencyindicator.html) can now be modified to 'Publishing Statistics', following agreement with the Global Partnership that this is now a process owned by IATI.

There was conversation at a recent internal team meeting that @jonihillman and Rohini would confirm copy changes needed for the page.  Just adding this issue so this is logged, and can be actioned when copy is available.

**Comment by hayfield** [comment]
#421
