### ISSUE TITLE
Add transaction/@humanitarian to booleans values reported by the IATI Dashboard

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Dashboard#416]
Separating a request from a comment in #413 into its own issue.

> Please could the values for transaction/@humanitarian attribute also be added the boolean page

**Comment by hayfield** [comment]
Re-opening since merging to master only leads to updates on the dev dashboard (next time it updates), and an additional action, merging to live, is required for the live dashboard to obtain this fix.

**Comment by wendyrogers** [comment]
This fix looks okay on the development dashboard at http://dev.dashboard.iatistandard.org/booleans.html so can be deployed to live.

Also , would it be possible to report the names of the organisations using any of the reported booleans by using their full publisher name eg Terre des Hommes NL rather that just reporting their publisher ID (tdh_nl)?

**Comment by hayfield** [comment]
This has been merged into the live branch. https://github.com/IATI/IATI-Stats/pull/87
