### ISSUE TITLE
Coverage using 2016 IATI Spend

### ISSUE THREAD

**Issue by bill-anderson** [IATI/IATI-Dashboard#426]
If a Publisher ONLY has 2016 transactions can we calculate coverage? Add highlighted logic.

Spend Ratio (%)

The IATI Spend as a percentage of the reference spending or the offical forecast. This value is based on whichever is the greatest result from the following calculations:

2014 IATI Spend / 2014 Reference Spend
2015 IATI Spend / 2015 Reference Spend
2015 IATI Spend / 2015 Official Forecast
2015 IATI Spend / 2014 Reference Spend (The resulting value from this calculation is only included if no annual pair of IATI Spend & Reference Spend/Offical Forecast data is available.)
**2016 IATI Spend / 2015 Reference Spend
2016 IATI Spend / 2014 Reference Spend**

**Comment by dalepotter** [comment]
It seems that this change would be made here: https://github.com/IATI/IATI-Dashboard/blob/master/coverage.py#L122-L126

**Comment by Mattdevinit** [comment]
Hi - has there been any progress on this please?  Worth adding to the diary at the end of the year too as presumably it'll need updating to reference 2017 data then?

**Comment by hayfield** [comment]
#443 is the latest

**Comment by Mattdevinit** [comment]
thanks @hayfield - must confess the content on #443 doesn't mean a lot to me!  Does this mean it's progressing/do you have an idea when it'll be done and live please?

**Comment by hayfield** [comment]
@Mattdevinit The changes were deployed to the dev Dashboard on Monday. The site has re-generated since then without things breaking, so it is likely that it will be deployed on the live Dashboard next week.

**Comment by Mattdevinit** [comment]
great thanks @hayfield, sounds good

**Comment by Mattdevinit** [comment]
thanks @hayfield for sorting this out and deploying to the live Dashboard, looks good

**Comment by hayfield** [comment]
Fixed, so closing
