### ISSUE TITLE
Non-standard elements/attributes are listed on the elements page

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Dashboard#432]
The [elements page](http://dashboard.iatistandard.org/elements.html) lists this typo, for instance:
http://dashboard.iatistandard.org/element/iati-activity_result_@aggreation-status.html

(`aggreation-status` instead of `aggregation-status`)

I understand this is probably by design, e.g. in order to include custom namespaces. But I wonder if it would be clearer to separate out the elements/attributes that are part of the standard from those that aren’t.

Refs #123.

**Comment by hayfield** [comment]
(the namespace theory is correct - see #381 )

**Comment by andylolz** [comment]
Given this threw @dalepotter and me, would you consider doing this?

> But I wonder if it would be clearer to separate out the elements/attributes that are part of the standard from those that aren’t.

**Comment by andylolz** [comment]
Hmm I don’t know why I opened this ticket – I think it’s just a duplicate of #123.
