### ISSUE TITLE
Error in API for IATI publishers list with details

### ISSUE THREAD

**Issue by timilsinabishal** [IATI/IATI-Dashboard#440]
The [API](https://iatiregistry.org/api/3/action/organization_list?all_fields=true) for fetching the list of publishers of IATI with their details is giving an error (ERR_CONNECTION_CLOSED).

**Comment by andylolz** [comment]
This is probably an issue for: https://github.com/ViderumGlobal/ckanext-iati

The query sometimes works, but it takes a loooong time so I imagine it sometimes times out.

As a workaround, I’d suggest splitting the query with `limit` and `offset` params i.e.:

 * https://iatiregistry.org/api/3/action/organization_list?all_fields=true&limit=20&offset=0
 * https://iatiregistry.org/api/3/action/organization_list?all_fields=true&limit=20&offset=20
 * …

**Comment by hayfield** [comment]
As mentioned by @andylolz, this is a CKAN issue rather than a Dashboard Issue.

Tagging @IATI/bas so they are aware.
