### ISSUE TITLE
Add list of IATI org IDs to the Dashboard

### ISSUE THREAD

**Issue by amy-silcock** [IATI/IATI-Dashboard#442]
Could we add a list of all reporting orgs and their IATI Org ID's onto the Dashboard? The nearest I can find is this page: http://dashboard.iatistandard.org/reporting_orgs.html. It should then make it easier for organisations to include participating org references in their data.

Thanks!

**Comment by wendyrogers** [comment]
Thanks for raising Amy and my preference would be to add a column containing the organisation identifier to the publisher list on the Registry at https://iatiregistry.org/publisher rather than on the dashboard? This has been discussed before but not taken forward. Therefore would be interested to get the views of others?

**Comment by PetyaKangalova** [comment]
@ wendy Yes, we discussed this with Viderum some time ago- see [Github issue](https://github.com/ViderumGlobal/ckanext-iati/issues/94), however, we are asking them to add the organisation identifiers to the admin interface.

I personally agree that it will be better to add the organisation identifiers to the Registry in here: https://www.iatiregistry.org/publisher.  New publisher will be more likely to go to the Registry to check the specific organisation identifier, than the Dashboard. I will now check with Viderum whether that will be possible and how long it will take to implement, so I think we can put this on hold for now.

**Comment by amy-silcock** [comment]
This is now on the IATI Registry. No longer needed on the Dashboard.

**Comment by andylolz** [comment]
Relatedly: Here’s a handy tool I made for looking up IATI organisation IDs that are self-declared in organisation files https://andylolz.github.io/org-id-finder/
