### ISSUE TITLE
Humanitarian - check and clarify

### ISSUE THREAD

**Issue by amy-silcock** [IATI/IATI-Dashboard#452]
In Humanitarian Reporting - Number of Activities

Need to check that the code picks up the @humanitarian attribute, DAC sector codes and Humanitarian Scope at both activity and transaction level. If yes at transaction level, how does this work with Appeals or Emergency Details?

(Here DAC sector codes refer to: DAC 5-digit sector codes between 72010 to 74010 inclusive, or DAC 3-digit sector codes 720, 730 or 740)

Then need to clarify this in Narrative.

(Also note that 'exceptions' and 'comment' are non-existent links)

**Comment by Ocre42** [comment]
Humanitarian attribute is being picked up at both transaction and activity levels, following DAC-5 and DAC-3 sector codes correctly. I'll be removing the exceptions and comments from the templates and then we can close this issue.
