### ISSUE TITLE
Forward looking - requires changes

### ISSUE THREAD

**Issue by amy-silcock** [IATI/IATI-Dashboard#454]
With the inclusion of `@budget-not provided `attribute as part of the 2.03 upgrade process, changes are required to the current methodology for forward-looking.

If` budget-not-provided` is present, the Dashboard logic should be that all required budgets exist.

As a result, the pseudocode on the [Forward-looking page](http://dashboard.iatistandard.org/forwardlooking.html) should change:
FROM:

> To calculate the "Current activities with budgets" column, count the number of activities that are:
> at a relevant hierarchical level (see above)
> AND current
> AND contain at least one budget budget with a budget year (as described above) that matches the year of the column 

 TO:
> To calculate the "Current activities with budgets" column, count the number of activities that are:
> at a relevant hierarchical level (see above)
> AND current
> AND contain at least one budget budget with a budget year (as described above) that matches the year of the column **OR contains budget-not-provided**

**Comment by Ocre42** [comment]
Sorted in #531
