### ISSUE TITLE
Comprehensiveness financials - requires changes

### ISSUE THREAD

**Issue by amy-silcock** [IATI/IATI-Dashboard#455]
Under[ Comprehensiveness- Financials](http://dashboard.iatistandard.org/comprehensiveness_financials.html), changes are required under:

1. Narrative:

> Budget
>For the hierarchy which contains the greatest number of budgets, the percentage of all current activities that contain at least one valid budget entry. A valid budget entry must contain a valid period-start AND a valid period-end AND a valid value AND a valid value-date.
> 

2. Pseudocode

Financials | Budget | Activity must have at least 1 budget element | Each budget element must contain period-start/@iso-date and period-end/@iso-date and value/@value-date that are valid xs:dates AND a value element that is a valid xs:decimal
-- | -- | -- | --

Both 1 and 2 need to incorporate the attribute `@budget-not-provided`.

**Comment by Ocre42** [comment]
Sorted in #535
