### ISSUE TITLE
Humanitarian dashboard doesn’t highlight which of the publishers are Grand Bargain signatories

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Dashboard#484]
It would be useful to be able to filter the humanitarian dashboard to show only those that are Grand Bargain signatories. This would help in measuring the progress of signatories against Grand Bargain commitments.

**Comment by PetyaKangalova** [comment]
For Grand Bargain signatories, there is a bespoke Dashboard in beta version accessible here: http://46.101.46.6/dashboard

**Comment by andylolz** [comment]
Oh! That’s very useful, thanks @PetyaKangalova!

Is that dashboard live? I.e. can it be referenced publicly?
