### ISSUE TITLE
Humanitarian dashboard: UNICEF scores almost 200% average

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Dashboard#488]
From [here](http://dev.dashboard.iatistandard.org/humanitarian.html):

![screen shot 2018-06-07 at 10 45 12](https://user-images.githubusercontent.com/464193/41092064-e85dc66e-6a3f-11e8-8399-999eeaaa4946.png)

This is a result of scoring 577% on “Appeal or Emergency Details”.

**Comment by stevieflow** [comment]
The blurn to describe this is:

> Use of humanitarian-scope element, both @type and @code must be present - proportion of the number of activities.

My understanding here is that the 577 is a count, rather than a proportion (of all humanitarian activities, or all activities?)

There's no Pseudocode for these metrics, so difficult to check further

**Comment by andylolz** [comment]
@stevieflow the explanation for this bug is in #489. The fix is in IATI/IATI-Stats#130.

**Comment by wendyrogers** [comment]
I think this one is a similar problem to that in #485 . The value calculated for the 'Emergency & Appeal' column needs amending so that it is calculated as the % of humanitarian activities that have at least 1 instance (or more) of the humanitarian-scope element specified. 

Also we will need to stick with the original definition of whether an activity is 'humanitarian' (or not) due to the definition having been generally accepted via the consultation for the Grand Bargain Transparency Dashboard methodology . Therefore, this means that if an activity has a humanitarian-scope element but neither the @humanitarian element or a relevant DAC sector code is present it will' NOT be considered as a 'humanitarian' activity.

**Comment by andylolz** [comment]
> The value calculated for the 'Emergency & Appeal' column needs amending so that it is calculated as the % of humanitarian activities that have at least 1 instance (or more) of the humanitarian-scope element specified.

^^ I’ve now made this change in IATI/IATI-Stats#133.

**Comment by andylolz** [comment]
Just to add a bit more explanation here… Here are five examples of UNICEF activities that are relevant here:

 * http://d-portal.org/q.xml?aid=41122-India-2040/A0/04/835/003
 * http://d-portal.org/q.xml?aid=41122-ROSA,%20Nepal-297R/A0/09/002/016
 * http://d-portal.org/q.xml?aid=41122-Barbados-0420/A0/04/002/002
 * http://d-portal.org/q.xml?aid=41122-Sierra%20Leone-3900/A0/07/882/006
 * http://d-portal.org/q.xml?aid=41122-WCARO,%20Senegal-381R/A0/09/800/001

In all cases above, the `@humanitarian` attribute is explicitly set to zero at both activity and transaction level:

```xml
<iati-activity […] humanitarian="0" […]>
```

(NB when an activity is explicitly declared as **not humanitarian** in this way, the activity is considered as not humanitarian by the dashboard, regardless of DAC codes.)

However, the `humanitarian-scope` element is declared:

```xml
<humanitarian-scope type="" vocabulary="" vocabulary-uri="" code="">
    <narrative xml:lang="en"/>
</humanitarian-scope>
```

Obviously all attributes are set to empty strings here, but the dashboard is still counting this as a `humanitarian-scope` element that has both a `@type` and a `@code` attribute. Even though the dashboard does not include this in the total count of humanitarian activities, it does include it in total number of activities with `Appeal or Emergency Details`. That’s how we end up with a number greater than 100% for this indicator.

**Comment by andylolz** [comment]
For clusters, we use the example of Stichting Vluchteling. Here are 5 relevant examples:

 * http://d-portal.org/q.html?aid=NL-KVK-41149486-CAR-15.1-DRA
 * http://d-portal.org/q.html?aid=NL-KVK-41149486-ETH-15.2-DRA
 * http://d-portal.org/q.html?aid=NL-KVK-41149486-SSDN-15.2-DRA
 * http://d-portal.org/q.html?aid=NL-KVK-41149486-IRQ-15.3-DRA
 * http://d-portal.org/q.html?aid=NL-KVK-41149486-IRQ-15.1-DRA

In all cases above, the @humanitarian attribute is explicitly set to zero at the activity level:

```xml
<iati-activity […] humanitarian="0" […]>
```

(NB it is sometimes set to 1 at the transaction level. However, the dashboard logic dictates that declaring zero at the activity level overrides that).

In all cases, `sector vocabulary="10"` is used, e.g.:

```xml
<sector code="PRO" percentage="40" vocabulary="10"/>
<sector code="FSC" percentage="60" vocabulary="10"/>
```

So these activities use the humanitarian global clusters vocabulary, but aren’t humanitarian activities by the dashboard definition (since they explicitly declare `humanitarian="0"` at activity level). So, as before, even though the dashboard doesn’t include these activities in the total count of humanitarian activities, it is including them in the total count of activities using clusters. Hence we end up with a number greater than 100%.

---

As a side note: In these cases, it looks like the publisher has actually made a mistake in declaring these activities as `@humanitarian="0"` at the activity level. These look like they are humanitarian activities. But that’s a separate data error.

**Comment by wendyrogers** [comment]
Just to add that to further complicate this issue I noticed that in many instances UNICEF have declared 'empty' values for humanitarian-scope eg 

<humanitarian-scope type="" vocabulary="" vocabulary-uri="" code="">
<narrative xml:lang="en"> </narrative>
</humanitarian-scope>

As a publishing principle we would ask publishers NOT to include elements unless they have any actual and valid content. However, in such instances where they have been included but are empty then they should be ignored and not counted within the publishing statistics

**Comment by andylolz** [comment]
Just noticed that #133 has now been deployed, so this is now fixed 👏 Maximum score for "Appeal or Emergency Details" is currently 100 👍

![screenshot 2019-02-05 at 12 16 35](https://user-images.githubusercontent.com/464193/52272850-f31db680-293f-11e9-90c9-923fdba6c151.png)
