### ISSUE TITLE
Humanitarian dashboard: definition of number of activities says it includes those using the `<humanitarian-scope>` element, but it doesn’t

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Dashboard#489]
The definition says:

> #### Number of Activities
> Total number of humanitarian activities (determined by use of `iati-activity/@humanitarian` attribute or `<humanitarian-scope>` element or DAC 5-digit sector codes between `72010` to `74010` inclusive, or DAC 3-digit sector codes `720`, `730` or `740`).

However, [the code says](https://github.com/IATI/IATI-Stats/blob/1d20ed1e711e6beecfe0a1a1415b08f9e60b3237/stats/dashboard.py#L1228-L1229):

```python
# combine the various ways in which an activity may be humanitarian
is_humanitarian = 1 if (is_humanitarian_by_attrib or is_humanitarian_by_sector) else 0
```

I.e. it checks whether either the `@humanitarian` attribute is set, or one or more of the relevant sector codes are used. But it doesn’t check for the `humanitarian-scope` element.

This is the reason for #488.

**Comment by andylolz** [comment]
> are you interpreting the requirement to be that an activity must ALSO include the humanitarian-scope element?

@stevieflow: No, I’m interpreting it as OR.

The important bit of my fix [is just here](https://github.com/IATI/IATI-Stats/pull/130/files#diff-8d798a043bf11b0238bf2d569a9c6f72L1228).

[The code currently](https://github.com/IATI/IATI-Stats/pull/130/files#diff-8d798a043bf11b0238bf2d569a9c6f72L1229) says:

```python
is_humanitarian = 1 if (is_humanitarian_by_attrib
                        or is_humanitarian_by_sector)
                    else 0
```

I.e. an activity should be included in the list of humanitarian activities if it uses the `@humanitarian` attribute, OR uses a humanitarian sector code.

[My fix changes it](https://github.com/IATI/IATI-Stats/pull/130/files#diff-8d798a043bf11b0238bf2d569a9c6f72L1231) to this:

```python
is_humanitarian = 1 if (is_humanitarian_by_attrib
                        or is_humanitarian_by_scope
                        or is_humanitarian_by_sector)
                    else 0
```

I.e. an activity should be included in the list of humanitarian activities if it uses the @humanitarian attribute, **OR uses the `<humanitarian-scope>` element,** OR uses a humanitarian sector code.

**Comment by stevieflow** [comment]
Excellent - thanks for the clarification @andylolz

**Comment by andylolz** [comment]
Basically the code and the definition don’t currently match. My fix makes them match.

I realised I could add a test to demonstrate it works, so I’ll do that. Thanks!

**Comment by wendyrogers** [comment]
Thanks for raising this issue @andylolz and I need to clarify that the definition of whether an activity is 'humanitarian' (or not) and which has been generally accepted via the consultation for the Grand Bargain Transparency Dashboard methodology is.

"Total number of humanitarian activities (determined by use of iati-activity/@humanitarian attribute or element or DAC 5-digit sector codes between 72010 to 74010 inclusive, or DAC 3-digit sector codes 720, 730 or 740)."

This means that if an activity has a humanitarian-scope element but neither the @humanitarian element or a relevant DAC sector code is present it should 'NOT be considered as a 'humanitarian' activity.

Therefore the definition for 'Number of Activities' needs to be amended to remove reference to humanitarian-scope element and we will also need to 'undo' the above fix

**Comment by wendyrogers** [comment]
Thanks @stevieflow and just to clarify that when I refer to the @humanitarian element I am referring to either
iati-activity/@humanitarian OR
iati-activity/transaction/@humanitarian

Does that help?

**Comment by stevieflow** [comment]
Thanks @wendyrogers - these are *attributes* though - the elements are ``iati-activity`` & ``transaction`` ?

**Comment by wendyrogers** [comment]
Haha ah yes @stevieflow my bad.  I shall make sure I am more specific in future and not use element in a more general sense

**Comment by stevieflow** [comment]
OK thanks @wendyrogers !

Going back to https://github.com/IATI/IATI-Dashboard/issues/489#issuecomment-396902912

What I'd like to clarify is if an activity is "humanitarian" in these cases

- It *only* has the humanitarian flag attribute at ``iati-activity`` and/or ``transaction`` level
- It *only* has the ``humanitarian-scope`` element populated
- It *only* has DAC sector codes between 72010 to 74010 inclusive, or DAC 3-digit sector codes 720, 730 or 740).

The methodology description (as @andylolz points out https://github.com/IATI/IATI-Dashboard/issues/489#issuecomment-395388931) implies that it is possible to have any of these, via use of OR

Thanks

**Comment by andylolz** [comment]
Here’s how the dashboard computes the “total number of humanitarian activities” for a publisher.

For each of the publisher’s activities:
 * If the activity has `iati-activity/@humanitarian` set to 1 or true, then **it’s humanitarian!**
 * If the activity has `iati-activity/@humanitarian` set to 0 or false, then **it’s not humanitarian!** (regardless of anything else!)
 * If `iati-activity/@humanitarian` **isn’t set**, then:
    - If for one or more transactions, `iati-activity/transaction/@humanitarian` is set to 1 or true, then **it’s humanitarian!**
    - if the activity uses one or more of the humanitarian DAC sector codes, then **it’s humanitarian!**

---

Important to note that the stuff in the number of humanitarian activities definition about `humanitarian-scope` is WRONG. I’ve changed it in #493.

**Comment by wendyrogers** [comment]
Just to confirm that as @andylolz points out the definition on the IATI dashboard incorrectly includes a reference to the use of the humanitarian-scope element and needs amending as per #493
