### ISSUE TITLE
Remove coverage columns in Publishing Statistics

### ISSUE THREAD

**Issue by samuele-mattiuzzo** [IATI/IATI-Dashboard#514]
> Following discussions with Bill, Kate, John, Petya and Sam, we have agreed:
>
> For devs to investigate how long it will take to remove the last two columns of the publisher statistics page (Coverage and Coverage Adjusted score): http://dashboard.iatistandard.org/summary_stats.html
>
>Agreement to keep the coverage page (http://dashboard.iatistandard.org/coverage.html) and add a banner that it is not up to date. Just added for reference.

**Comment by samuele-mattiuzzo** [comment]
This is now done and up for code review. We won't merge and deploy untill we have set a deadline and informed publishers

**Comment by andylolz** [comment]
This looks done and deployed, and can be closed :tada:
