### ISSUE TITLE
All OCHA Country Based Pooled Funds missing from dashboard

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Dashboard#538]
See:
http://dashboard.iatistandard.org/publisher/unocha-cbpf.html

I think the problem is: to get the data as XML, you have to preferentially accept XML via the HTTP headers ([like this](https://github.com/andylolz/IATI-Registry-Refresher/commit/bc07cf4269da60b06ec9056ce6630aa7ed9325e0)). IATI-Registry-Refresher doesn’t do this.

**Comment by andylolz** [comment]
[d-portal is also thrown by this](http://d-portal.org/ctrack.html?publisher=XM-OCHA-CBPF#view=main), so perhaps it’s fair to call this a publisher error?

**Comment by samuele-mattiuzzo** [comment]
Seems like they had issues pushing to the Registry as well; I know we raised this with Derilinx, although I can't find it on Git so I'm guessing it happened via email.
Fair to assume publisher error I think (still your PR :+1: )

**Comment by davidmegginson** [comment]
When I looked at the CBPF XML a few days ago, I noticed a spurious empty _script_ element before the first _iati-activity,_ and that was causing XML schema validation to fail. They know about the problem now.

**Comment by andylolz** [comment]
> When I looked at the CBPF XML a few days ago, I noticed a spurious empty _script_ element before the first _iati-activity,_ and that was causing XML schema validation to fai

Ohhhh – so, that one might be another problem!

To give an example of the issue I’m talking about: this file renders fine in my browser:
https://cbpfapi.unocha.org/iati/iati/19/2019/GetAllocation.xml

…but that’s because browsers preferentially accept HTML or XML (via the q param of the `Accept` header).

If I request it programmatically and don’t explicitly set the `Accept` header to prefer XML, I get JSON that looks like this:
https://gist.githubusercontent.com/andylolz/f304a8546449e2f73becc58ba8b9af99/raw/e1f14879dd03d2e2daae7066c4d2b0044178a31d/unocha-cbpf-southsudan-2019.json

**Comment by davidmegginson** [comment]
Yes, I'm seeing that too.

**Comment by andylolz** [comment]
Issue looks fixed at the CBPF end :clap: I expect the dashboard will pick up the data when it next runs. V impressive response time!

I’ll leave this ticket open, just until they reappear on the dashboard.

**Comment by andylolz** [comment]
Forgot to check back on this! They’re back on the dashboard, so I’ll close this.
