### ISSUE TITLE
Dashboard not updating? (Last updated 20 May 2019)

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Dashboard#546]
[Apologies for pointing out dates here, but it’s really important to the ticket since it helps establish there’s a problem.]

The dashboard is scheduled to update every 3 days, but hasn’t updated in 11 days. So it looks like there’s a problem.

~~It looks likely that [IATI-Stats](https://github.com/IATI/IATI-Stats) is also broken, since [some of the stats](http://dashboard.iatistandard.org/stats/gitaggregate-publisher-dated/?C=M;O=D) haven’t been updated in the last 6 days. This is an issue at least in part because the historical stats produced are super interesting and useful for [making](https://public.flourish.studio/visualisation/392689/) [lovely](https://public.flourish.studio/visualisation/390691/) [graphs](https://public.flourish.studio/visualisation/390509/)!~~ Good news – IATI-Stats no longer looks broken :star2:

I guess this is a known issue since there are efforts to resolve it (#545), but there wasn’t a public ticket for it so here it is.

It seems as though the problem is: some SSOT-related code that is relied on has been modified to support python 3, and no longer supports python 2.7. I wonder if the simplest solution might be to (at least temporarily) make the code that’s relied upon support both python 3 and python 2.7. What do you think?

**Comment by samuele-mattiuzzo** [comment]
we'll look at it on monday

**Comment by samuele-mattiuzzo** [comment]
Our Python environment and the server that runs the Dashboard are currently slightly broken (it has to do with the version of Ubuntu we have on the servers and Python's SSL support).

We're going to look into that to fix it within the next few days

**Comment by andylolz** [comment]
> version of Ubuntu we have on the servers and Python's SSL support

Interesting… Can you elaborate?

It sounds like a separate problem from the one I identified, which related to python2.7 support being dropped by dependencies.

**Comment by samuele-mattiuzzo** [comment]
Servers are on Ubuntu 14.04 that does not come with Python 3.x shipped by default (v17 onwards).
While installing Python, we could not have `_ssl` support for some reason, so we tried the manual compilation route to no avail. This is preventing `pip` from functioning correctly and our attempts at fixing them might have also affected the Python 2.x installation.

We're doing the same update on the dev dashboard server, which is in a slightly better place. I think we're going to try to have the dev instance up and running so that we can then just switch the dns and have that as our live instance while we spend more time fixing the other one.

**Comment by andylolz** [comment]
Cool – thanks for the update @samuele-mattiuzzo.

> I think we're going to try to have the dev instance up and running so that we can then just switch the dns and have that as our live instance while we spend more time fixing the other one.

This sounds like a great approach.

**Comment by samuele-mattiuzzo** [comment]
A server snapshot has been restored (coincidence: 20th of May we had a snapshot!) and the Python 2.7 installation seems to have been restored and Pip2 can now work again without ssl issues.

This doesn't mean the Dashboard has regenerated *yet* .

Next step: upgrade ubuntu from 14.04 to 17.x which would hopefully enable us to have a clean python3 install

**Comment by andylolz** [comment]
> A server snapshot has been restored (coincidence: 20th of May we had a snapshot!) and the Python 2.7 installation seems to have been restored and Pip2 can now work again without ssl issues.

Great! 👏 

> Next step: upgrade ubuntu from 14.04 to 17.x which would hopefully enable us to have a clean python3 install

Is it still the plan to do this work on the dev server / on some server that is not live, and then once it’s all working, switch the DNS? I think that approach is still good.

**Comment by samuele-mattiuzzo** [comment]
Yes, that's still the idea: I'll create a copy/clone of the server (not that easy with VPS.net, they're not the best ... after I clicked on "restore snapshot", a spinner came up for 2 seconds then the dashboard page for the server popped up with no info whatsoever on what just happened) and do the work on that

For what concerns #547 it should already be in, I will now check properly and eventually upgrade the checked out version

**Comment by samuele-mattiuzzo** [comment]
<img width="516" alt="Screenshot 2019-06-05 at 3 56 39 pm" src="https://user-images.githubusercontent.com/1381563/58966696-aa212600-87aa-11e9-842a-c510c5f745e1.png">

I guess we'll be pending 🤷‍♂

**Comment by stevieflow** [comment]
Hi @samuele-mattiuzzo - any news on this?  It's particularly pressing as the "timeliness" metrics would have updated with us now being in June.  Thanks

**Comment by samuele-mattiuzzo** [comment]
Hi @stevieflow no, unfortunately not many updates on this, our host is taking ages to create a snapshot of the machine (see screenshot above) and I am not keen on trialling anything on the live server to avoid breaking the DB even further. We sorted some python/ssl issues for 2.7 though, so the DB should have been regenerated (hopefully?) although it was only 2 days ago, we might have to wait till end of day today/weekend to see updated results

**Comment by andylolz** [comment]
> I am not keen on trialling anything on the live server to avoid breaking the DB even further.

+1, this sounds sensible.

> We sorted some python/ssl issues for 2.7 though, so the DB should have been regenerated (hopefully?)

Can you check the generated log files to see how far the latest build has got?

> our host is taking ages to create a snapshot of the machine

Is it still running?! 2 days is a reeeeeally long time for this. What's going on there?!

**Comment by samuele-mattiuzzo** [comment]
Good question, I have no idea and no way of checking either (VPS.net). Click on "copy snapshot", get taken back to the homepage, go visit the servers page, no extra info is added about the process/status anything, except for that table I screenshotted.

Worse thing of all, I'm creating a template, that I can then use to create a new server and I don't expect a different outcome than the above. I got in touch with them via email, but I guess I won't hear back any time soon :(

I checked out that branch specifically to try it btw, but it seems to still be running (kicked off yesterday morning apparently). I'll check again over the weekend, really sorry this is taking so long because of all this waiting time :(

**Comment by stevieflow** [comment]
Hi @samuele-mattiuzzo - really appreciate you looking into this.  It doesn't look like the weekend brought us any results - any further news?

**Comment by samuele-mattiuzzo** [comment]
Not yet. When we will have an update, we will post. Thanks for your patience.

**Comment by samuele-mattiuzzo** [comment]
`webserver9` has been restored and the Dashboard rebuild is due to run between today and tomorrow, we'll see then if it's fixed.
In the meantime, we're going to set up the droplet to replace `webserver11` as the `dev.dashboard`, and hopefully move away from VPS if that goes well, which could sync up to the split.

**Comment by samuele-mattiuzzo** [comment]
```
The Dashboard is generated routinely, with the last update based on data in the IATI Registry on 19 May 2019 (at 06:46). We expect the Dashboard to update every few days, for more information, see the FAQ.
```

@stevieflow is everything you need in there now?

**Comment by andylolz** [comment]
Brilliant – looks good to me.

Thanks for sorting this, @samuele-mattiuzzo.

**Comment by samuele-mattiuzzo** [comment]
> Brilliant – looks good to me.
> 
> Thanks for sorting this, @samuele-mattiuzzo.

/cc @Ocre42 ^

**Comment by stevieflow** [comment]
Great stiff @samuele-mattiuzzo @Ocre42 - appreciate your diligence and patience!

Yes - already met a *newly minted* monthly publisher this morning :)

**Comment by andylolz** [comment]
This was (at least in part) resolved by adding python2 support back into IATI-Codelists, right?

**Comment by Ocre42** [comment]
@andylolz Adding support for python2.7 and restoring a previous instance of the dashboard has helped, the dev dashboard is still having some issues, but I'm currently working to whip up a new one (and hopefully making it a lot easier to deploy any new instances)

**Comment by andylolz** [comment]
Great – thanks!

I did my best to deploy it to github pages using heroku, but unfortunately the memory usage is way too high for heroku:
https://github.com/andylolz/dashboard

If you’re running into issues, there’s a chance it’s memory-related. I’m kind of interested in trying to build a more clientside version, since the server-generated graphs are not easy to read anyway.
