### ISSUE TITLE
High memory usage during make_html.py

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Dashboard#550]
While #495 massively speeds up the build process, it also uses huge amounts of memory. The amount of memory used scales with publishers & elements, so it may eventually become a problem.

It might be worth thinking about how to tackle this as part of the python3 upgrade?

**Comment by samuele-mattiuzzo** [comment]
We're in the middle of splitting Dashboard and Publishers Stats, we'll consider this once that is done.

Thanks
