### ISSUE TITLE
Templates are exposed on the frontend

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Dashboard#551]
E.g. http://dashboard.iatistandard.org/static/templates/publisher.html

It’s a consequence of 33d08ebb6846c245c780c177f8c7b17132b43a9e. Everything in /static is exposed on the frontend, but templates needn’t be.

**Comment by samuele-mattiuzzo** [comment]
That template code being rendered in Firefox looks neater than the Dashboard's UI itself.

😭

**Comment by andylolz** [comment]
Ha! It is quite satisfying to look at. I almost think it should stay, as an easter egg!

In any case, I don’t think it does any harm, since these templates are part of the open source code anyway.

**Comment by andylolz** [comment]
I already closed the related PR, and I don’t think this issue matters really. Closing.
