### ISSUE TITLE
BUG: `odc-by` license is missing a name

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Dashboard#553]
There are three licenses without a "license name" on this page:
http://dashboard.iatistandard.org/licenses.html

These are:

 * `None` – I’m not sure why this would be part of this list. I guess this is an issue with registry data, or with the registry API. Should probably be updated to `notspecified` in the data
 * `pddl` – I think this is a bug on the registry. I’ve created a ticket for that here: IATI/ckanext-iati#255
 * `odc-by` – this refers to [the Open Data Commons Attribution license](https://opendatacommons.org/licenses/by/1-0/index.html). This is a valid license, which the registry allows users to select:
    ![Screenshot 2019-06-18 at 12 35 12](https://user-images.githubusercontent.com/464193/59679091-da62be80-91c5-11e9-8e8c-095a1185559f.png)

For the title to be shown, the license needs to be included in licenses.py

**Comment by andylolz** [comment]
In fact, [ODC-BY](http://dashboard.iatistandard.org/license/odc-by.html) is the second-to-most popular license choice.

**Comment by Ocre42** [comment]
There's a few bugs that have popped up because of the licensing changes, I'll make sure to pick this one up, alongside the Registry Refresher not updating the ckan metadata, thanks for pointing this out @andylolz

**Comment by andylolz** [comment]
Great – thanks @Ocre42. Don’t know if you saw, but I sent a fix for this: #554.

**Comment by andylolz** [comment]
Okay [this looks good](http://dashboard.iatistandard.org/licenses.html):

![Screenshot 2019-07-08 at 14 30 05](https://user-images.githubusercontent.com/464193/60814081-e6bab580-a18c-11e9-9799-0696a5508369.png)
