### ISSUE TITLE
Bug: There’s sometimes a 6 day gap between dashboard updates

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Dashboard#559]
The [Dashboard FAQ](http://dashboard.iatistandard.org/faq.html) says:

> ### When is the Dashboard updated?
> The Dashboard is generated through a process that starts shortly after midnight UK time on the following days each month:
> 
> 1st, 4th, 7th, 10th, 13th, 16th, 19th, 22nd, 25th (and the 28th for months with 31 days)

This schedule is designed to ensure there is always at least 3 days between dashboard updates, so that updates do not overlap.

According to this schedule, on months with 30 days, the dashboard runs on the 25th, and then 6 days later on the 1st. 6 days is a long time between updates. Also, 6 is divisible by 3. So for months with 30 days, it’s possible to do an additional run on the 28th and still allow 3 days for the update process to complete.

**Comment by Ocre42** [comment]
This is likely to be rendered irrelevant once the dashboard and publisher-stats split takes place, given that they'll be running separately and we will be able to update them daily. (and is actually already the case in the dev instance of the dashboard)

**Comment by andylolz** [comment]
Sounds good! Do you mind leaving this ticket open until it's resolved? I.e. until the new solution is deployed and the dashboard is updating more frequently. Thanks

**Comment by Ocre42** [comment]
Dashboard and Publishing Stats split has now gone live, regeneration is now performed daily, I'll be closing this ticket now.

**Comment by andylolz** [comment]
That’s great! Congrats / thanks!

**Comment by samuele-mattiuzzo** [comment]
Excellent job @Ocre42 !

This issue now needs no further commenting
