### ISSUE TITLE
Add CSV redirects to publishingstats.iatistandard.org

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Dashboard#564]
It looks like the relevant HTML pages have been redirected from dashboard.iatistandard.org to publishingstats.iatistandard.org. But CSV downloads haven’t been redirected, and the previous URLs now 404. For example:
http://dashboard.iatistandard.org/timeliness_frequency.csv

Would it be possible to add those redirects, too? I guess this would mean adding […]`\.(?:html|csv)$` or similar to one or more regexes.

I mention this because the aid transparency index methodology relies on the timeliness frequency statistics, and this change broke the import.

I appreciate this is not an official API, so there’s no requirement to maintain these URLs.

Thanks

**Comment by andylolz** [comment]
I feel like it’s always good to reference [“Cool URIs don’t change”](https://www.w3.org/Provider/Style/URI), as the seminal work on the subject.

**Comment by samuele-mattiuzzo** [comment]
We'll look at this, sensible suggestion indeed, thanks @andylolz

**Comment by andylolz** [comment]
Excellent – many thanks

**Comment by Ocre42** [comment]
Redirects have been merged and updated in IATI-Websites as well.

**Comment by andylolz** [comment]
Excellent – thanks for resolving this so swiftly!

**Comment by andylolz** [comment]
Excellent – thanks for resolving this so swiftly
