### ISSUE TITLE
Initial data import starts before "Doing initial data import" message

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Dashboard#571]
**Describe the bug**
licenses.py imports from data.py, causing the initial data import to happen before the "Doing initial data import" message.

**To Reproduce**
1. Run `python make_html.py`
2. Wait a long time without any message
3. See the following message all at once:
    ```
    Doing initial data import
    Initial data import finished
    ```

**Comment by samuele-mattiuzzo** [comment]
Tried, reviewed and merged, thanks @andylolz !

John will follow up after my departure on Thursday re deployments and whatnots
