### ISSUE TITLE
"validator" links no longer show validation results

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Dashboard#585]
**Describe the bug**
I [raised this on IATI Connect](https://iaticonnect.org/comment/reply/node/1804/field_discussion_comments/9310), but creating an issue for visibility.

"validator" links on the Dashboard (e.g. [on this page](http://dashboard.iatistandard.org/validation.html), but also on publisher pages) previously linked to validation results. Now that the new validator is live, they instead link to the validator homepage.

**To Reproduce**
1. Go to http://dashboard.iatistandard.org/validation.html
2. Scroll down to “List of files that fail validation, grouped by publisher”
3. Click on a “validator” link
4. See the IATI Validator homepage

**Expected behavior**
I expect to instead see validation results. That was the previous behaviour.

**Comment by PetyaKangalova** [comment]
@andylolz apologies for the delay in getting back to you.

**Validator API**: As you know we are currently working on validator API. The request parameters in the API contract will include url as a parameter. Once the validator API is live we will be able to use it to link to other tools, such as the Dashboard. However, at the moment the links to the home validator page is the best option that we can offer via the Dashboard.

**Linking Validator results to the Dashboard:** only once the validator API is live, we will be able to link to other tools, such as the IATI Dashboard. We will be launching a consultation with our community on a new Data Quality Index  later this quarter and will then review how our users would like to see their validator stats presented and whether that should be linked to the Dashboard. This would hopefully address your user need on presenting validator results per publisher. It will be great to have your input once the consultation has launched.

**Comment by andylolz** [comment]
@PetyaKangalova thanks for the response.

It’s not a problem for me. I just noticed the issue and thought I’d flag it.

I don’t know if there are other links "in the wild" that now point to the validator homepage, but the old validator did suggest to publishers that they provide these validator links for their users: https://github.com/IATI/IATI-Public-Validator/blob/bd678c7d/developers.php#L24-L26

**Comment by PetyaKangalova** [comment]
The validator API is now live. so the links have now been replaced with the new validator links: http://dashboard.iatistandard.org/validation.html. That is for files that were already listed there.

**Comment by andylolz** [comment]
That’s great – thanks for the update.

In that case I think this ticket is resolved.
