### ISSUE TITLE
Broken Link to Validator

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Dashboard#597]
**Describe the bug**
Broken Link to Validator

**To Reproduce**
http://dashboard.iatistandard.org/publisher/unops.html

Data Quality / Files Failing Validation section

validator links to http://validator.iatistandard.org/?url=https%3A//storage.googleapis.com/unops-iati-datafiles/data/iati/20230714/iati-activities/iati_activity_AE.xml

**Expected behavior**

I go to a page for that file

**Actual behavior**

I get dumped at validator home page and nothing happens

**Comment by akmiller01** [comment]
Should be an easy fix. Where the URL to the registry for the file is http://iatiregistry.org/dataset/unops-ae

The valid link to the validator for the file uses the same ID: https://validator.iatistandard.org/report/unops-ae

**Comment by chrisarridge** [comment]
Fully closed in PR https://github.com/IATI/IATI-Dashboard/pull/613.
