### ISSUE TITLE
IATI Dashboard no longer active?

### ISSUE THREAD

**Issue by siemvaessen** [IATI/IATI-Dashboard#598]
Tried reaching the IATI Dashboard as per link here: https://iatistandard.org/en/iati-tools-and-resources/  but seems https://dashboard.iatistandard.org/ is not reachable? Was this decommissioned and I just forgot about it?!

Edit: seems no SSL is in place and hence first message is not reachable. It is - just w/o SSL which probably bad practice, could that be fixed?

**Comment by ghost** [comment]
So the page you mention does link to http://dashboard.iatistandard.org/ (no SSL) - do you have some extension installed that enforces HTTPS?

However soon this will solve itself - we have already announced a move to new hosting and that hosting does have SSL. https://www.iaticonnect.org/topic/changes-iati-dashboard-publisher-stats-early-2024

**Comment by ghost** [comment]
SSL is now available.
