### ISSUE TITLE
Be more clear about activity vs organisation file distinction

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Dashboard#78]
Sometimes the dashboard is talking about all files, sometimes it's only activity files - this distinction should be more clear, or the functionality changed to be more obvious.

As an example http://dashboard.iatistandard.org/element/iati-activity_@hierarchy.html lists the number of files with that element, but it is an element that only appears in activity files (so this number can be at maximum the number of activity files). However, the total number of files which is provided for comparison includes both organisation and activity files.

**Comment by allthatilk** [comment]
General improvements of documentation is for a future project.
